inherit_gem:
  jekyll: .rubocop.yml

AllCops:
  Include:
    - lib/**/*.rb
  Exclude:
    - benchmark/**/*
    - script/**/*
    - vendor/**/*
Metrics/LineLength:
  Exclude:
    - ./**/*.gemspec
    - ./**/Gemfile
    - !ruby/regexp /features\/.*.rb/
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: no_comma
