script: script/cibuild
cache: bundler
language: ruby
sudo: false

rvm:
  - &ruby1 2.3.1
  - &ruby2 2.2.5
  - &ruby3 2.1.9
  - &jruby jruby-9.1.2.0

matrix:
  include:
    - rvm: *ruby1
      env: TEST_SUITE=fmt
  exclude:
    - rvm: *jruby
      env: TEST_SUITE=cucumber

env:
  matrix:
    - TEST_SUITE=test
    - TEST_SUITE=cucumber
